---
- name: Create hash from password for user
  command: openssl passwd -1 "{{ password }}"
  register: password_of_user


- name: Configure ocpasswd file and create a user
  lineinfile: dest="{{ src_vol }}/ocpasswd"
              line='{{item}}'
  with_items:
    - "{{ username }}:Route,All:{{ password_of_user.stdout }}"


- name: Deploy ocserv docker container
  docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        published_ports:
          - "{{ src_port }}:{{ dest_port }}"
          - "{{ src_port }}:{{ dest_port }}/udp"
        volumes:
          - "{{ src_vol }}:{{ dest_vol }}"
        privileged: "{{ privileged }}"
        restart_policy: always
        env:
           CA_CN: "{{ CA_CN }}"
           CA_ORG: "{{ CA_ORG }}"
           CA_DAYS: "{{ CA_DAYS }}"
           SRV_CN: "{{ node_ip }}"
           SRV_ORG: "{{ SRV_ORG }}"
           SRV_DAYS: "{{ SRV_DAYS }}"
           NO_TEST_USER: "{{ NO_TEST_USER }}"
