# create a directory if it doesn't exist
- file:
    path: "{{ src_vol }}"
    state: directory
    mode: 0755

# touch the file
- file:
    path: "{{ src_vol }}/ocpasswd"
    state: touch

# copy configuration file
- name: Configure ocserv
  template:
    src: ocserv.conf.j2
    dest: "{{ src_vol }}/ocserv.conf"
    backup: yes

#install packages
- name : install packages
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - docker

# install python2-pip package
- name : install pip 2 package
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python2-pip

#install docker-py package
- name : install docker-py with pip
  pip:
    name: docker-py
    executable: pip
