# create a directory if it doesn't exist
- file:
    path: "{{ src_vol }}"
    state: directory
    mode: 0755

# touch the ocpasswd file
- file:
    path: "{{ src_vol }}/ocpasswd"
    state: touch

# copy configuration file
- name: Configure ocserv
  template:
    src: ocserv.conf.j2
    dest: "{{ src_vol }}/ocserv.conf"
    backup: yes
